name: Release

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    name: PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine

      - name: Build
        run: python setup.py sdist

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
